# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
pillar = YAML.load_file('../pillar/platform/local.sls')

install_salt_sh = <<SCRIPT
#!/bin/sh

echo "10.0.2.2 salt" >> /etc/hosts

add-apt-repository -y ppa:saltstack/salt
apt-get update
apt-get -y install salt-minion
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  pillar["hosts"].each do |hostname, ip|
    config.vm.define hostname do |box|
      box.vm.hostname = hostname
      box.vm.network "public_network", ip: ip
    end
  end

  config.vm.provision "shell", inline: install_salt_sh
end
