# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'
pillar = YAML.load_file('../pillar/platform/local.sls')

master_ip = File.read('master-ip')

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"

  config.ssh.forward_agent = true
  config.ssh.forward_x11 = true

  pillar["hosts"].each do |hostname, ip|
    config.vm.define hostname do |box|
      box.vm.hostname = hostname
      box.vm.network "public_network", ip: ip
    end
  end

  config.vm.provision "shell", path: "install_salt.sh", args: master_ip
end
