# Name for grid deployment and documentation.
application: IceCap

services:
  - name: Demo
    setup: icecap.demo.server.init
    replicated: both
  - name: SmallFS
    setup: icecap.storage.small_fs.server
    replicated: true
  - name: DataManager
    setup: icecap.storage.data_manager.server
    replicated: true

# Used by documentation generator
author: Oliver Goodman
year: 2015

autodoc:
  icecap.base: Basic infrastructure
  icecap.base.antenna: Server environment servant
  icecap.base.cap_dict: Dictionary of objects
  icecap.base.env: Environment resource factory
  icecap.base.env_base: Common environment methods
  icecap.base.future: Asynchronous return values
  icecap.base.lru_cache: Least-recently-used Cache
  icecap.base.master: Master-slave election
  icecap.base.publisher: Publish-subscribe base class
  icecap.base.thread_pool: A simple thread-pool
  icecap.base.util: Basic utilities

  icecap.data: Persistent data
  icecap.data.data_array: Persistent sequence of strings with cached indexing
  icecap.data.data_log: Persistent sequence of strings
  icecap.data.file_dict: Persistent dictionary of strings

  icecap.demo: Demo services
  icecap.demo.event_source: An observable servant
  icecap.demo.person: A serializable object
  icecap.demo.printer: A simple demo servant
  icecap.demo.server: Demo server

  icecap.storage: Data storage
  icecap.storage.data_client: Client proxy wrapper for working with DataNodes
  icecap.storage.data_manager: Handles operations involving multiple DataNodes
  icecap.storage.data_node: Base servant for data storage
  icecap.storage.data_relay: Data synchronisation and replication
  icecap.storage.data_shard: Base class for data sharding and replication
  icecap.storage.small_fs: A replicated file store

  icecap.ti: Test infrastructure
  icecap.ti.fake_grid: Fake grid and resource factory
