# Name for grid deployment and documentation.
application: IceCap

services:
  - name: Demo
    setup: icecap.demo.server.init
    replicated: both
  - name: SmallFS
    setup: icecap.file.small_fs.server
    replicated: true

# Used by documentation generator
author: Oliver Goodman
year: 2014

autodoc:
  icecap.base: Basic infrastructure
  icecap.base.antenna: Server environment servant
  icecap.base.env: Environment resource factory
  icecap.base.env_base: Common environment methods
  icecap.base.future: Asynchronous return values
  icecap.base.master: Master-slave election
  icecap.base.publisher: Publish-subscribe base class
  icecap.base.rep_log: Log which pushes updates to followers
  icecap.base.thread_pool: A simple thread-pool
  icecap.base.util: Basic utilities

  icecap.data: Persistent data
  icecap.data.data_log: Persistent sequence of strings

  icecap.demo: Demo services
  icecap.demo.event_source: An observable servant
  icecap.demo.printer: A simple demo servant
  icecap.demo.server: Demo server

  icecap.file: File storage
  icecap.file.small_fs: A replicated file store

  icecap.ti: Test infrastructure
  icecap.ti.fake_grid: Fake grid and resource factory
