# Name for grid deployment and documentation.
application: IceCap

services:
  - name: Demo
    setup: icecap.demo.server.init
    replicated: both

# Used by documentation generator
author: Oliver Goodman
year: 2014

autodoc:
  icecap.base: Basic infrastructure
  icecap.base.env: Environment resource factory
  icecap.base.master: Master-slave election
  icecap.base.rep_log: Log which pushes updates to followers
  icecap.base.util: Basic utilities

  icecap.data: Persistent data
  icecap.data.data_log: Persistent sequence of strings

  icecap.demo: Demo services
  icecap.demo.event_log: Observable with persistent event log
  icecap.demo.event_source: An observable servant
  icecap.demo.file: A replicated file store
  icecap.demo.printer: A simple demo servant
  icecap.demo.server: Demo server

  icecap.ti: Test infrastructure
  icecap.ti.fake_grid: Fake grid and resource factory
