# Name for grid deployment and documentation.
application: IceCap

services:
  - name: Demo
    setup: icecap.servers.demo.setup
    replicated: both

# Used by documentation generator
author: Oliver Goodman
year: 2014

autodoc:
  icecap.base: Basic infrastructure
  icecap.base.env: Environment resource factory
  icecap.base.event_source: An observable servant
  icecap.base.master: Master-slave election
  icecap.base.util: Basic utilities

  icecap.demo: Demo servants
  icecap.demo.printer: A simple demo servant

  icecap.ti: Test infrastructure
  icecap.ti.fake_grid: Fake grid and resource factory
